-- 역할(app_api 등)은 클러스터 전역 객체이고 다른 DB에서 쓰일 수 있으므로 삭제하지 않는다.
DROP SCHEMA IF EXISTS analyst CASCADE;
DROP SCHEMA IF EXISTS auth CASCADE;
DROP SCHEMA IF EXISTS ingest CASCADE;
DROP SCHEMA IF EXISTS core CASCADE;
DROP SCHEMA IF EXISTS config CASCADE;
DROP SCHEMA IF EXISTS util CASCADE;
