-- =====================================================================
-- 0002 종목 설정 (config)
--  종목별 차이는 모두 이 테이블들로 표현한다. 값은 config/sports/*.yaml 을
--  `python -m app.cli sync-config` 로 동기화해 채운다.
-- =====================================================================

-- 종목
CREATE TABLE config.sport (
    id               smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             text NOT NULL UNIQUE CHECK (code ~ '^[a-z][a-z0-9_]*$'),
    name_ko          text NOT NULL,
    name_en          text NOT NULL,
    period_label_ko  text NOT NULL,                 -- 이닝 / 쿼터 / 세트 / 하프
    score_unit_ko    text NOT NULL,                 -- 점 / 골
    clock_type       text NOT NULL CHECK (clock_type IN ('none', 'countdown', 'countup')),
    settings         jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(settings) = 'object'),
    is_active        boolean NOT NULL DEFAULT true,
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now()
);

-- 경기 구간 정의 (이닝, 쿼터, 세트, 전·후반, 연장 ...)
CREATE TABLE config.period_definition (
    id                    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_id              smallint NOT NULL REFERENCES config.sport (id),
    code                  text NOT NULL CHECK (code ~ '^[A-Z][A-Z0-9_]*$'),
    name_ko               text NOT NULL,
    label_pattern         text NOT NULL,            -- 예: '{n}회', '{n}쿼터', '연장 {n}'
    regulation_count      smallint NOT NULL CHECK (regulation_count >= 0),   -- 정규 구간 수 (연장류는 0)
    max_count             smallint CHECK (max_count IS NULL OR max_count >= regulation_count),
    is_overtime           boolean NOT NULL DEFAULT false,
    nominal_duration_sec  integer CHECK (nominal_duration_sec IS NULL OR nominal_duration_sec > 0),
    sort_order            smallint NOT NULL DEFAULT 0,
    is_active             boolean NOT NULL DEFAULT true,
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),
    UNIQUE (sport_id, code)
);

-- 포지션
CREATE TABLE config.position_definition (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_id        smallint NOT NULL REFERENCES config.sport (id),
    code            text NOT NULL CHECK (code ~ '^[A-Z0-9][A-Z0-9_]*$'),
    name_ko         text NOT NULL,
    name_en         text NOT NULL,
    position_group  text NOT NULL,                  -- 예: 내야수 / 가드 / 수비수
    sort_order      smallint NOT NULL DEFAULT 0,
    is_active       boolean NOT NULL DEFAULT true,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (sport_id, code)
);

-- 경기 내 이벤트 타입
CREATE TABLE config.event_type_definition (
    id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_id           smallint NOT NULL REFERENCES config.sport (id),
    code               text NOT NULL CHECK (code ~ '^[A-Z][A-Z0-9_]*$'),
    name_ko            text NOT NULL,
    participant_roles  text[] NOT NULL DEFAULT '{}',   -- 예: {batter,pitcher}
    attr_schema        jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(attr_schema) = 'object'),  -- JSON Schema
    sort_order         smallint NOT NULL DEFAULT 0,
    is_active          boolean NOT NULL DEFAULT true,
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now(),
    UNIQUE (sport_id, code)
);

-- 지표 카테고리 (타격/투구/수비, 슈팅/리바운드 ...). 지표 코드 접두어와 일치한다.
CREATE TABLE config.stat_category (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_id        smallint NOT NULL REFERENCES config.sport (id),
    code            text NOT NULL CHECK (code ~ '^[a-z][a-z0-9]*$'
                                         AND code NOT IN ('lg', 'ctx', 'team', 'opp', 'cm', 'cf')),
    name_ko         text NOT NULL,
    name_en         text NOT NULL,
    sort_order      smallint NOT NULL DEFAULT 0,
    is_active       boolean NOT NULL DEFAULT true,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (sport_id, code),
    UNIQUE (id, sport_id)      -- stat_definition 의 복합 FK 대상 (같은 종목 보장)
);

-- 지표 정의: 화면 컬럼, 차트 축, 검증, 파생 계산이 모두 이 테이블을 읽는다.
--  code 규칙: [카테고리.]대문자코드  (예: bat.HR, pit.ERA, PTS)
--  data_type: int(정수) / decimal(소수) / ratio(.xxx 표기) / percent(0~1 저장, % 표기)
--             / innings(아웃카운트/3, 6.1 표기) / duration(초) / text
--  aggregation: 상위 레벨로 롤업하는 방법. formula 는 구성 요소를 먼저 합산한 뒤 수식을 재적용.
CREATE TABLE config.stat_definition (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_id          smallint NOT NULL REFERENCES config.sport (id),
    category_id       integer NOT NULL,
    code              text NOT NULL CHECK (code ~ '^([a-z][a-z0-9]*\.)?[A-Z][A-Z0-9_]*$'),
    name_ko           text NOT NULL,
    name_en           text NOT NULL,
    abbr              text NOT NULL,
    scope             text NOT NULL CHECK (scope IN ('player', 'team', 'both')),
    levels            text[] NOT NULL CHECK (cardinality(levels) > 0
                                             AND levels <@ ARRAY['period', 'match', 'season']::text[]),
    unit              text,
    data_type         text NOT NULL CHECK (data_type IN ('int', 'decimal', 'ratio', 'percent',
                                                         'innings', 'duration', 'text')),
    aggregation       text NOT NULL CHECK (aggregation IN ('sum', 'avg', 'max', 'min', 'last',
                                                           'formula', 'none')),
    decimals          smallint NOT NULL DEFAULT 0 CHECK (decimals BETWEEN 0 AND 6),
    higher_is_better  boolean,                      -- NULL = 중립 (경기 수, 타석 등)
    is_derived        boolean NOT NULL DEFAULT false,
    formula           text,
    depends_on        text[] NOT NULL DEFAULT '{}', -- 수식이 참조하는 코드 (sync-config 가 자동 산출)
    is_hot            boolean NOT NULL DEFAULT false, -- 경기 기록 테이블에 식 인덱스 생성 대상
    display_order     integer NOT NULL DEFAULT 0,
    description       text,
    is_active         boolean NOT NULL DEFAULT true,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    UNIQUE (sport_id, code),
    FOREIGN KEY (category_id, sport_id) REFERENCES config.stat_category (id, sport_id),
    CONSTRAINT stat_definition_derived_has_formula CHECK (is_derived = (formula IS NOT NULL)),
    CONSTRAINT stat_definition_formula_aggregation CHECK (is_derived = (aggregation = 'formula'))
);
CREATE INDEX ix_stat_definition_display ON config.stat_definition (sport_id, category_id, display_order);

-- 리그 상수 정의 (wOBA 가중치, FIP 상수, 리그 평균 ...). 값은 시즌별로 config.league_constant 에 저장.
--  formula 가 있으면 리그 합계(팀 시즌 기록 합산)로부터 배치 계산, 없으면 수동 입력/수집 값.
CREATE TABLE config.league_constant_definition (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_id     smallint NOT NULL REFERENCES config.sport (id),
    code         text NOT NULL CHECK (code ~ '^[A-Z][A-Z0-9_]*$'),
    name_ko      text NOT NULL,
    formula      text,
    depends_on   text[] NOT NULL DEFAULT '{}',
    decimals     smallint NOT NULL DEFAULT 4 CHECK (decimals BETWEEN 0 AND 8),
    description  text,
    is_active    boolean NOT NULL DEFAULT true,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    UNIQUE (sport_id, code)
);

-- 스플릿 기준. sport_id NULL 은 모든 종목 공통 (홈/원정, 월별, 상대팀, 경기장 ...)
--  key_expression 은 스플릿 엔진이 해석하는 경로 (match.* / period.* / event.* / player.*)
CREATE TABLE config.split_definition (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_id        smallint REFERENCES config.sport (id),
    code            text NOT NULL CHECK (code ~ '^[a-z][a-z0-9_]*$'),
    name_ko         text NOT NULL,
    source          text NOT NULL CHECK (source IN ('match', 'period', 'event', 'player')),
    key_expression  text NOT NULL CHECK (key_expression ~ '^(match|period|event|player)\.[a-z_][a-z0-9_.]*$'),
    value_labels    jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(value_labels) = 'object'),
    sort_order      smallint NOT NULL DEFAULT 0,
    description     text,
    is_active       boolean NOT NULL DEFAULT true,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_split_definition UNIQUE NULLS NOT DISTINCT (sport_id, code),
    CONSTRAINT split_definition_source_matches_key CHECK (key_expression LIKE source || '.' || '_%')
);

-- 리더보드 자격 조건 (규정 타석/이닝, 최소 출전 시간 ...)
--  rule_expression 예: 'bat.PA >= 3.1 * ctx.TEAM_GAMES'
CREATE TABLE config.qualification_rule (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_id         smallint NOT NULL REFERENCES config.sport (id),
    category_id      integer NOT NULL,
    code             text NOT NULL CHECK (code ~ '^[a-z][a-z0-9_]*$'),
    name_ko          text NOT NULL,
    rule_expression  text NOT NULL,
    depends_on       text[] NOT NULL DEFAULT '{}',
    is_provisional   boolean NOT NULL DEFAULT false,  -- 공식 기준 미확인 (임시값)
    description      text,
    is_active        boolean NOT NULL DEFAULT true,
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    UNIQUE (sport_id, code),
    FOREIGN KEY (category_id, sport_id) REFERENCES config.stat_category (id, sport_id)
);

SELECT util.attach_updated_at_trigger(t)
FROM unnest(ARRAY[
    'config.sport', 'config.period_definition', 'config.position_definition',
    'config.event_type_definition', 'config.stat_category', 'config.stat_definition',
    'config.league_constant_definition', 'config.split_definition', 'config.qualification_rule'
]::regclass[]) AS t;
