-- =====================================================================
-- 0003 데이터 소스 + 리그 계층 (League → Season → Competition Stage) + 리그 상수 값
-- =====================================================================

-- 데이터 소스 (수집 대상 사이트).
--  collection_allowed 가 true 가 되기 전에는 수집기가 요청을 보내지 않는다.
--  (robots.txt·이용약관 검토 결과를 terms_note 에 남기고 관리자가 켠다)
CREATE TABLE ingest.data_source (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                text NOT NULL UNIQUE CHECK (code ~ '^[a-z][a-z0-9_]*$'),
    name                text NOT NULL,
    base_url            text NOT NULL,
    terms_url           text,
    robots_url          text,
    robots_checked_at   timestamptz,
    terms_checked_at    timestamptz,
    terms_note          text,
    collection_allowed  boolean NOT NULL DEFAULT false,
    min_interval_ms     integer NOT NULL DEFAULT 3000 CHECK (min_interval_ms >= 500),
    max_retries         smallint NOT NULL DEFAULT 3 CHECK (max_retries BETWEEN 0 AND 10),
    user_agent          text,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now()
);

-- 리그/대회
CREATE TABLE core.league (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_id       smallint NOT NULL REFERENCES config.sport (id),
    code           text NOT NULL UNIQUE CHECK (code ~ '^[A-Z][A-Z0-9_]*$'),
    name_ko        text NOT NULL,
    name_en        text NOT NULL,
    country        char(2) NOT NULL,
    gender         text NOT NULL CHECK (gender IN ('men', 'women', 'mixed')),
    tier           smallint NOT NULL DEFAULT 1 CHECK (tier >= 1),
    timezone       text NOT NULL,
    collector_key  text,                            -- 수집 플러그인 키
    settings       jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(settings) = 'object'),
    is_active      boolean NOT NULL DEFAULT true,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);

-- 시즌. 기간은 수집기가 일정 수집 시 채운다 (비시즌 판단 기준).
CREATE TABLE core.season (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id     integer NOT NULL REFERENCES core.league (id),
    label         text NOT NULL,                    -- '2026', '2025-26'
    start_year    smallint NOT NULL,
    start_date    date,
    end_date      date,
    status        text NOT NULL DEFAULT 'upcoming' CHECK (status IN ('upcoming', 'active', 'completed')),
    source_id     integer REFERENCES ingest.data_source (id),
    collected_at  timestamptz,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    UNIQUE (league_id, label),
    CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
);

-- 대회 단계 (정규시즌, 포스트시즌, 파이널 라운드 ...)
CREATE TABLE core.competition_stage (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_id     integer NOT NULL REFERENCES core.season (id),
    code          text NOT NULL CHECK (code ~ '^[A-Z][A-Z0-9_]*$'),
    name_ko       text NOT NULL,
    stage_type    text NOT NULL CHECK (stage_type IN ('preseason', 'regular', 'postseason',
                                                      'group', 'knockout', 'cup', 'relegation')),
    start_date    date,
    end_date      date,
    sort_order    smallint NOT NULL DEFAULT 0,
    source_id     integer REFERENCES ingest.data_source (id),
    collected_at  timestamptz,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    UNIQUE (season_id, code),
    UNIQUE (id, season_id),    -- (stage_id, season_id) 복합 FK 대상: 시즌 비정규화 컬럼의 일관성 보장
    CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
);

-- 시즌별 리그 상수 값
CREATE TABLE config.league_constant (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_id      integer NOT NULL REFERENCES core.season (id),
    definition_id  integer NOT NULL REFERENCES config.league_constant_definition (id),
    value          numeric NOT NULL,
    origin         text NOT NULL CHECK (origin IN ('computed', 'collected', 'manual')),
    note           text,
    computed_at    timestamptz NOT NULL DEFAULT now(),
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    UNIQUE (season_id, definition_id)
);

-- 시즌 → 리그 → 종목 문맥 (자주 쓰는 조인)
CREATE VIEW core.v_season_context AS
SELECT s.id    AS season_id,
       s.label AS season_label,
       l.id    AS league_id,
       l.code  AS league_code,
       sp.id   AS sport_id,
       sp.code AS sport_code,
       l.timezone
FROM core.season s
JOIN core.league l   ON l.id = s.league_id
JOIN config.sport sp ON sp.id = l.sport_id;

SELECT util.attach_updated_at_trigger(t)
FROM unnest(ARRAY[
    'ingest.data_source', 'core.league', 'core.season', 'core.competition_stage', 'config.league_constant'
]::regclass[]) AS t;
