-- =====================================================================
-- 0004 수집 관리 (ingest): 스케줄, 실행 로그, raw 원문, 외부 ID 매핑
-- =====================================================================

-- 리그별 수집 작업 스케줄. dispatcher 가 주기적으로 읽어 due 작업을 큐에 넣는다.
CREATE TABLE ingest.collection_schedule (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id         integer NOT NULL REFERENCES core.league (id),
    source_id         integer NOT NULL REFERENCES ingest.data_source (id),
    job_type          text NOT NULL CHECK (job_type IN ('schedule', 'results', 'boxscore', 'events',
                                                        'season_stats', 'standings', 'roster', 'players')),
    cron              text NOT NULL,                -- 5필드 cron, timezone 기준
    timezone          text NOT NULL,
    offseason_policy  text NOT NULL DEFAULT 'skip' CHECK (offseason_policy IN ('skip', 'run', 'weekly')),
    enabled           boolean NOT NULL DEFAULT true,
    params            jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(params) = 'object'),
    last_enqueued_at  timestamptz,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    UNIQUE (league_id, source_id, job_type)
);

-- 수집 실행 로그
CREATE TABLE ingest.ingest_run (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id    integer REFERENCES ingest.collection_schedule (id) ON DELETE SET NULL,
    league_id      integer REFERENCES core.league (id),
    source_id      integer REFERENCES ingest.data_source (id),
    job_type       text NOT NULL,
    trigger        text NOT NULL CHECK (trigger IN ('schedule', 'manual', 'reprocess', 'backfill')),
    status         text NOT NULL DEFAULT 'running'
                   CHECK (status IN ('running', 'success', 'partial', 'failed', 'skipped')),
    params         jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(params) = 'object'),
    -- 건수: {"fetched":..,"inserted":..,"updated":..,"unchanged":..,"rejected":..}
    counts         jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(counts) = 'object'),
    warnings       jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(warnings) = 'array'),
    error_message  text,
    error_detail   jsonb,
    started_at     timestamptz NOT NULL DEFAULT now(),
    finished_at    timestamptz,
    alerted_at     timestamptz,
    CHECK (finished_at IS NULL OR finished_at >= started_at),
    CHECK (status = 'running' OR finished_at IS NOT NULL)
);
CREATE INDEX ix_ingest_run_league_started ON ingest.ingest_run (league_id, started_at DESC);
CREATE INDEX ix_ingest_run_status ON ingest.ingest_run (status, started_at DESC) WHERE status IN ('running', 'failed', 'partial');

-- 원문 (HTML/JSON). 파서를 고치면 재요청 없이 이 테이블에서 재처리한다.
CREATE TABLE ingest.raw_payload (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id       integer NOT NULL REFERENCES ingest.data_source (id),
    ingest_run_id   bigint REFERENCES ingest.ingest_run (id) ON DELETE SET NULL,
    document_type   text NOT NULL CHECK (document_type ~ '^[a-z][a-z0-9_]*$'),  -- schedule / boxscore / ...
    external_key    text NOT NULL,                  -- 소스 내 문서 식별자 (경기 ID, 날짜 등)
    request_url     text NOT NULL,
    request_method  text NOT NULL DEFAULT 'GET',
    request_params  jsonb,
    http_status     smallint,
    content_type    text,
    body            bytea,
    body_encoding   text NOT NULL DEFAULT 'identity' CHECK (body_encoding IN ('identity', 'gzip', 'zstd')),
    object_key      text,                           -- 외부 오브젝트 스토리지 사용 시
    sha256          char(64) NOT NULL,              -- 압축 전 원문 해시
    size_bytes      integer NOT NULL CHECK (size_bytes >= 0),
    fetched_at      timestamptz NOT NULL DEFAULT now(),
    parser_version  smallint,
    parse_status    text NOT NULL DEFAULT 'pending' CHECK (parse_status IN ('pending', 'parsed', 'failed', 'skipped')),
    parse_error     text,
    parsed_at       timestamptz,
    CHECK (body IS NOT NULL OR object_key IS NOT NULL),
    CONSTRAINT uq_raw_payload_content UNIQUE (source_id, document_type, external_key, sha256)
);
CREATE INDEX ix_raw_payload_lookup ON ingest.raw_payload (source_id, document_type, external_key, fetched_at DESC);
CREATE INDEX ix_raw_payload_parse ON ingest.raw_payload (parse_status) WHERE parse_status IN ('pending', 'failed');

-- 외부 ID ↔ 내부 ID 매핑 (다형 참조라 DB FK 없음 → core.v_external_id_orphans 로 점검)
CREATE TABLE ingest.external_id_map (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id      integer NOT NULL REFERENCES ingest.data_source (id),
    entity_type    text NOT NULL CHECK (entity_type IN ('league', 'season', 'stage', 'team', 'player',
                                                        'venue', 'match')),
    external_id    text NOT NULL,
    entity_id      bigint NOT NULL,
    confidence     text NOT NULL DEFAULT 'exact' CHECK (confidence IN ('exact', 'fuzzy', 'manual')),
    first_seen_at  timestamptz NOT NULL DEFAULT now(),
    last_seen_at   timestamptz NOT NULL DEFAULT now(),
    UNIQUE (source_id, entity_type, external_id)
);
CREATE INDEX ix_external_id_map_entity ON ingest.external_id_map (entity_type, entity_id);

-- 자동 매핑 실패(동명이인 등) 검토 대기열
CREATE TABLE ingest.id_match_candidate (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id            integer NOT NULL REFERENCES ingest.data_source (id),
    entity_type          text NOT NULL,
    external_id          text NOT NULL,
    payload              jsonb NOT NULL,            -- 소스가 준 식별 정보 (이름, 생년월일, 팀 ...)
    candidate_ids        bigint[] NOT NULL DEFAULT '{}',
    status               text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'resolved', 'rejected')),
    resolved_entity_id   bigint,
    resolved_by          integer,                   -- auth.app_user.id (스키마 순서상 FK 는 0007 에서 추가)
    ingest_run_id        bigint REFERENCES ingest.ingest_run (id) ON DELETE SET NULL,
    created_at           timestamptz NOT NULL DEFAULT now(),
    resolved_at          timestamptz,
    UNIQUE (source_id, entity_type, external_id)
);

SELECT util.attach_updated_at_trigger('ingest.collection_schedule'::regclass);
