-- =====================================================================
-- 0005 공통 엔티티 + 자동 수집 기록 (core)
--  - 쓰기 주체는 수집 워커(app_ingest)뿐이다. API(app_api)는 SELECT 권한만 가진다 (0007).
--  - 모든 수집 레코드는 출처(source_id), 수집 실행(ingest_run_id), 수집 시각(collected_at)을 가진다.
--  - 기록 값은 stats(수집 원시 지표) / derived(파생 지표) JSONB 에 stat_definition.code 키로 저장한다.
-- =====================================================================

-- 경기장 (여러 종목·팀이 공유할 수 있어 종목에 묶지 않는다)
CREATE TABLE core.venue (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_ko        text NOT NULL,
    name_en        text,
    city           text,
    capacity       integer CHECK (capacity IS NULL OR capacity > 0),
    latitude       numeric(9, 6),
    longitude      numeric(9, 6),
    attrs          jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(attrs) = 'object'),  -- 돔 여부, 잔디 등
    source_id      integer REFERENCES ingest.data_source (id),
    ingest_run_id  bigint REFERENCES ingest.ingest_run (id) ON DELETE SET NULL,
    collected_at   timestamptz,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);

-- 스포츠 팀 (구단). 리그 소속은 시즌 단위로 core.season_team 에 둔다 (승강제 대응).
CREATE TABLE core.team (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_id        smallint NOT NULL REFERENCES config.sport (id),
    code            text,                           -- 약칭 코드 (LG, KIA ...)
    name_ko         text NOT NULL,
    name_en         text,
    short_name_ko   text,
    city            text,
    founded_year    smallint,
    home_venue_id   integer REFERENCES core.venue (id),
    attrs           jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(attrs) = 'object'),
    is_active       boolean NOT NULL DEFAULT true,
    source_id       integer REFERENCES ingest.data_source (id),
    ingest_run_id   bigint REFERENCES ingest.ingest_run (id) ON DELETE SET NULL,
    collected_at    timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_team_sport ON core.team (sport_id, name_ko);

-- 팀 명칭 변경 이력 (연고지 이전, 스폰서 변경)
CREATE TABLE core.team_name_history (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id        integer NOT NULL REFERENCES core.team (id) ON DELETE CASCADE,
    valid_from     date NOT NULL,
    valid_to       date,
    name_ko        text NOT NULL,
    short_name_ko  text,
    name_en        text,
    UNIQUE (team_id, valid_from),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- 시즌 참가 팀
CREATE TABLE core.season_team (
    season_id     integer NOT NULL REFERENCES core.season (id),
    team_id       integer NOT NULL REFERENCES core.team (id),
    group_code    text NOT NULL DEFAULT '',         -- 조/컨퍼런스 (없으면 빈 문자열)
    source_id     integer REFERENCES ingest.data_source (id),
    collected_at  timestamptz,
    PRIMARY KEY (season_id, team_id)
);

-- 선수. 종목 고유 속성(투타, 주발 등)은 attrs 에 둔다.
CREATE TABLE core.player (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_id       smallint NOT NULL REFERENCES config.sport (id),
    name_ko        text NOT NULL,
    name_en        text,
    birth_date     date,
    nationality    text,
    height_cm      numeric(5, 1),
    weight_kg      numeric(5, 1),
    attrs          jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(attrs) = 'object'),
    source_id      integer REFERENCES ingest.data_source (id),
    ingest_run_id  bigint REFERENCES ingest.ingest_run (id) ON DELETE SET NULL,
    collected_at   timestamptz,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_player_sport_name ON core.player (sport_id, name_ko);

-- 소속·등록 이력 (1군 등록/말소, 이적, 임대, 군 복무 ...)
CREATE TABLE core.roster_entry (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id      integer NOT NULL REFERENCES core.player (id),
    team_id        integer NOT NULL REFERENCES core.team (id),
    season_id      integer NOT NULL REFERENCES core.season (id),
    valid_from     date NOT NULL,
    valid_to       date,
    status         text NOT NULL CHECK (status IN ('active', 'reserve', 'injured', 'loan', 'military', 'released')),
    jersey_no      text,
    position_code  text,                            -- config.position_definition.code (앱에서 검증)
    source_id      integer REFERENCES ingest.data_source (id),
    ingest_run_id  bigint REFERENCES ingest.ingest_run (id) ON DELETE SET NULL,
    collected_at   timestamptz,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    UNIQUE (player_id, team_id, season_id, valid_from),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);
CREATE INDEX ix_roster_entry_team ON core.roster_entry (team_id, season_id);

-- 경기
CREATE TABLE core.match (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_id      integer NOT NULL,
    stage_id       integer NOT NULL,
    home_team_id   integer NOT NULL REFERENCES core.team (id),
    away_team_id   integer NOT NULL REFERENCES core.team (id),
    venue_id       integer REFERENCES core.venue (id),
    scheduled_at   timestamptz NOT NULL,
    local_date     date NOT NULL,                   -- 리그 타임존 기준 경기일 (자연키)
    game_number    smallint NOT NULL DEFAULT 1 CHECK (game_number >= 1),  -- 더블헤더 순번
    round_label    text,                            -- 라운드 (K리그 R1, V-리그 1라운드 ...)
    status         text NOT NULL DEFAULT 'scheduled'
                   CHECK (status IN ('scheduled', 'live', 'final', 'postponed', 'cancelled', 'suspended', 'forfeit')),
    home_score     smallint CHECK (home_score IS NULL OR home_score >= 0),
    away_score     smallint CHECK (away_score IS NULL OR away_score >= 0),
    winner         text CHECK (winner IN ('home', 'away', 'draw')),
    result_type    text CHECK (result_type ~ '^[A-Z][A-Z0-9_]*$'),  -- REG / OT / PSO / CALLED ...
    attendance     integer CHECK (attendance IS NULL OR attendance >= 0),
    duration_sec   integer CHECK (duration_sec IS NULL OR duration_sec >= 0),
    started_at     timestamptz,
    ended_at       timestamptz,
    attrs          jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(attrs) = 'object'),
    source_id      integer REFERENCES ingest.data_source (id),
    ingest_run_id  bigint REFERENCES ingest.ingest_run (id) ON DELETE SET NULL,
    collected_at   timestamptz,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (stage_id, season_id) REFERENCES core.competition_stage (id, season_id),
    CHECK (home_team_id <> away_team_id),
    CHECK (status <> 'final' OR (home_score IS NOT NULL AND away_score IS NOT NULL)),
    CONSTRAINT uq_match_natural UNIQUE (stage_id, home_team_id, away_team_id, local_date, game_number)
);
CREATE INDEX ix_match_scheduled ON core.match (scheduled_at);
CREATE INDEX ix_match_season_date ON core.match (season_id, local_date);
CREATE INDEX ix_match_home ON core.match (home_team_id, scheduled_at);
CREATE INDEX ix_match_away ON core.match (away_team_id, scheduled_at);

-- 경기 구간 (이닝/쿼터/세트/하프/연장). ordinal 은 경기 내 전체 순서 (Q4 다음 OT1 = 5)
CREATE TABLE core.match_period (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id       bigint NOT NULL REFERENCES core.match (id) ON DELETE CASCADE,
    period_def_id  integer NOT NULL REFERENCES config.period_definition (id),
    seq            smallint NOT NULL CHECK (seq >= 1),
    ordinal        smallint NOT NULL CHECK (ordinal >= 1),
    home_score     smallint CHECK (home_score IS NULL OR home_score >= 0),
    away_score     smallint CHECK (away_score IS NULL OR away_score >= 0),
    duration_sec   integer CHECK (duration_sec IS NULL OR duration_sec >= 0),
    stats          jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(stats) = 'object'),
    source_id      integer REFERENCES ingest.data_source (id),
    ingest_run_id  bigint REFERENCES ingest.ingest_run (id) ON DELETE SET NULL,
    collected_at   timestamptz,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    UNIQUE (match_id, period_def_id, seq),
    UNIQUE (match_id, ordinal),
    UNIQUE (id, match_id)      -- 기록 테이블의 (period_id, match_id) 복합 FK 대상
);

-- 선발/출전 명단
CREATE TABLE core.match_lineup (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id       bigint NOT NULL REFERENCES core.match (id) ON DELETE CASCADE,
    team_id        integer NOT NULL REFERENCES core.team (id),
    player_id      integer NOT NULL REFERENCES core.player (id),
    is_starter     boolean NOT NULL,
    order_no       smallint,                        -- 타순 등
    position_code  text,
    shirt_no       text,
    attrs          jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(attrs) = 'object'),
    source_id      integer REFERENCES ingest.data_source (id),
    ingest_run_id  bigint REFERENCES ingest.ingest_run (id) ON DELETE SET NULL,
    collected_at   timestamptz,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    UNIQUE (match_id, player_id)
);
CREATE INDEX ix_match_lineup_player ON core.match_lineup (player_id);

-- 선수 경기 기록. period_id NULL = 경기 전체, 값이 있으면 해당 구간 기록 (쿼터별/세트별)
CREATE TABLE core.player_match_stat (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id       bigint NOT NULL REFERENCES core.match (id) ON DELETE CASCADE,
    player_id      integer NOT NULL REFERENCES core.player (id),
    team_id        integer NOT NULL REFERENCES core.team (id),
    period_id      bigint,
    position_code  text,
    is_starter     boolean,
    stats          jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(stats) = 'object'),
    derived        jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(derived) = 'object'),
    derived_at     timestamptz,
    source_id      integer REFERENCES ingest.data_source (id),
    ingest_run_id  bigint REFERENCES ingest.ingest_run (id) ON DELETE SET NULL,
    collected_at   timestamptz,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (period_id, match_id) REFERENCES core.match_period (id, match_id) ON DELETE CASCADE,
    CONSTRAINT uq_player_match_stat UNIQUE NULLS NOT DISTINCT (match_id, player_id, period_id)
);
CREATE INDEX ix_player_match_stat_player ON core.player_match_stat (player_id, match_id);
CREATE INDEX ix_player_match_stat_team ON core.player_match_stat (team_id, match_id);

-- 팀 경기 기록
CREATE TABLE core.team_match_stat (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id       bigint NOT NULL REFERENCES core.match (id) ON DELETE CASCADE,
    team_id        integer NOT NULL REFERENCES core.team (id),
    period_id      bigint,
    stats          jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(stats) = 'object'),
    derived        jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(derived) = 'object'),
    derived_at     timestamptz,
    source_id      integer REFERENCES ingest.data_source (id),
    ingest_run_id  bigint REFERENCES ingest.ingest_run (id) ON DELETE SET NULL,
    collected_at   timestamptz,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (period_id, match_id) REFERENCES core.match_period (id, match_id) ON DELETE CASCADE,
    CONSTRAINT uq_team_match_stat UNIQUE NULLS NOT DISTINCT (match_id, team_id, period_id)
);
CREATE INDEX ix_team_match_stat_team ON core.team_match_stat (team_id, match_id);

-- 선수 시즌 누적 기록
--  team_id NULL = 시즌 합산 (이적 선수는 팀별 행 + 합산 행)
--  origin: collected(소스 공식 누적) / aggregated(경기 기록 합산, 누락 탐지·스플릿 기반)
CREATE TABLE core.player_season_stat (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_id      integer NOT NULL,
    stage_id       integer NOT NULL,
    player_id      integer NOT NULL REFERENCES core.player (id),
    team_id        integer REFERENCES core.team (id),
    origin         text NOT NULL CHECK (origin IN ('collected', 'aggregated')),
    stats          jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(stats) = 'object'),
    derived        jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(derived) = 'object'),
    derived_at     timestamptz,
    source_id      integer REFERENCES ingest.data_source (id),
    ingest_run_id  bigint REFERENCES ingest.ingest_run (id) ON DELETE SET NULL,
    collected_at   timestamptz,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (stage_id, season_id) REFERENCES core.competition_stage (id, season_id),
    CONSTRAINT uq_player_season_stat UNIQUE NULLS NOT DISTINCT (stage_id, player_id, team_id, origin)
);
CREATE INDEX ix_player_season_stat_player ON core.player_season_stat (player_id, season_id);

-- 팀 시즌 누적 기록
CREATE TABLE core.team_season_stat (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_id      integer NOT NULL,
    stage_id       integer NOT NULL,
    team_id        integer NOT NULL REFERENCES core.team (id),
    origin         text NOT NULL CHECK (origin IN ('collected', 'aggregated')),
    stats          jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(stats) = 'object'),
    derived        jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(derived) = 'object'),
    derived_at     timestamptz,
    source_id      integer REFERENCES ingest.data_source (id),
    ingest_run_id  bigint REFERENCES ingest.ingest_run (id) ON DELETE SET NULL,
    collected_at   timestamptz,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (stage_id, season_id) REFERENCES core.competition_stage (id, season_id),
    CONSTRAINT uq_team_season_stat UNIQUE (stage_id, team_id, origin)
);
CREATE INDEX ix_team_season_stat_team ON core.team_season_stat (team_id, season_id);

-- 순위표 스냅숏 (날짜별). 순위 지표(승/패/승점 ...)는 stat_definition category 'std'
CREATE TABLE core.standing (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stage_id       integer NOT NULL REFERENCES core.competition_stage (id),
    team_id        integer NOT NULL REFERENCES core.team (id),
    as_of_date     date NOT NULL,
    rank           smallint NOT NULL CHECK (rank >= 1),
    group_code     text NOT NULL DEFAULT '',
    stats          jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(stats) = 'object'),
    source_id      integer REFERENCES ingest.data_source (id),
    ingest_run_id  bigint REFERENCES ingest.ingest_run (id) ON DELETE SET NULL,
    collected_at   timestamptz,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    UNIQUE (stage_id, team_id, as_of_date)
);
CREATE INDEX ix_standing_latest ON core.standing (stage_id, as_of_date DESC);

-- 경기 내 이벤트 (타석, 슛, 득점, 교체, 카드 ...). 경기일 기준 연 단위 범위 파티션.
CREATE TABLE core.event (
    id                bigint GENERATED BY DEFAULT AS IDENTITY,
    match_date        date NOT NULL,                -- 파티션 키 (= match.local_date)
    match_id          bigint NOT NULL REFERENCES core.match (id) ON DELETE CASCADE,
    period_id         bigint,
    seq               integer NOT NULL CHECK (seq >= 1),  -- 경기 내 순번
    event_type_id     integer NOT NULL REFERENCES config.event_type_definition (id),
    team_id           integer REFERENCES core.team (id),
    clock_sec         integer,                      -- 경기 시계 (남은 시간 또는 경과 시간, sport.clock_type 기준)
    elapsed_sec       integer,                      -- 경기 시작부터 경과 (가능한 경우)
    score_home_after  smallint,
    score_away_after  smallint,
    description       text,                         -- 소스 원문 설명
    attrs             jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(attrs) = 'object'),
    source_id         integer REFERENCES ingest.data_source (id),
    ingest_run_id     bigint REFERENCES ingest.ingest_run (id) ON DELETE SET NULL,
    collected_at      timestamptz,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id, match_date),
    FOREIGN KEY (period_id, match_id) REFERENCES core.match_period (id, match_id) ON DELETE CASCADE,
    CONSTRAINT uq_event_seq UNIQUE (match_id, seq, match_date)
) PARTITION BY RANGE (match_date);
CREATE INDEX ix_event_type ON core.event (event_type_id, match_date);

-- 연도 파티션 생성 헬퍼 (수집 워커가 새 시즌 시작 전에 호출)
CREATE FUNCTION util.ensure_event_partition(p_year integer) RETURNS void
LANGUAGE plpgsql AS $$
DECLARE
    part_name text := 'event_y' || p_year::text;
BEGIN
    IF to_regclass('core.' || part_name) IS NULL THEN
        EXECUTE 'CREATE TABLE core.' || quote_ident(part_name)
             || ' PARTITION OF core.event FOR VALUES FROM ('
             || quote_literal(make_date(p_year, 1, 1)) || ') TO ('
             || quote_literal(make_date(p_year + 1, 1, 1)) || ')';
    END IF;
END $$;

CREATE TABLE core.event_default PARTITION OF core.event DEFAULT;
SELECT util.ensure_event_partition(y) FROM generate_series(2023, 2027) AS y;

-- 이벤트 참여자 (타자/투수, 슈터/어시스트, 교체 IN/OUT ...)
CREATE TABLE core.event_participant (
    event_id    bigint NOT NULL,
    match_date  date NOT NULL,
    player_id   integer NOT NULL REFERENCES core.player (id),
    role        text NOT NULL CHECK (role ~ '^[a-z][a-z0-9_]*$'),
    ord         smallint NOT NULL DEFAULT 1,
    PRIMARY KEY (event_id, role, player_id),
    FOREIGN KEY (event_id, match_date) REFERENCES core.event (id, match_date) ON DELETE CASCADE
);
CREATE INDEX ix_event_participant_player ON core.event_participant (player_id, role);

SELECT util.attach_updated_at_trigger(t)
FROM unnest(ARRAY[
    'core.venue', 'core.team', 'core.player', 'core.roster_entry', 'core.match', 'core.match_period',
    'core.match_lineup', 'core.player_match_stat', 'core.team_match_stat', 'core.player_season_stat',
    'core.team_season_stat', 'core.standing', 'core.event'
]::regclass[]) AS t;

-- ---------------------------------------------------------------------
-- 정합성 점검 (야간 배치가 조회, 결과가 있으면 알림)
-- ---------------------------------------------------------------------

-- JSONB 키 중 해당 종목 stat_definition 에 없는 코드. p_derived 는 derived 컬럼 여부.
CREATE FUNCTION util.undefined_stat_keys(p_sport_id smallint, p_stats jsonb, p_derived boolean)
RETURNS text[]
LANGUAGE sql STABLE AS $$
    SELECT coalesce(array_agg(k ORDER BY k), '{}')
    FROM jsonb_object_keys(p_stats) AS k
    WHERE NOT EXISTS (
        SELECT 1 FROM config.stat_definition sd
        WHERE sd.sport_id = p_sport_id AND sd.code = k AND sd.is_derived = p_derived
    )
$$;

CREATE VIEW core.v_stat_key_violations AS
WITH rows AS (
    SELECT 'player_match_stat' AS table_name, x.id AS row_id, m.season_id, x.stats, x.derived
    FROM core.player_match_stat x JOIN core.match m ON m.id = x.match_id
    UNION ALL
    SELECT 'team_match_stat', x.id, m.season_id, x.stats, x.derived
    FROM core.team_match_stat x JOIN core.match m ON m.id = x.match_id
    UNION ALL
    SELECT 'player_season_stat', x.id, x.season_id, x.stats, x.derived FROM core.player_season_stat x
    UNION ALL
    SELECT 'team_season_stat', x.id, x.season_id, x.stats, x.derived FROM core.team_season_stat x
    UNION ALL
    SELECT 'standing', x.id, cs.season_id, x.stats, '{}'::jsonb
    FROM core.standing x JOIN core.competition_stage cs ON cs.id = x.stage_id
), checked AS (
    SELECT r.table_name, r.row_id, c.sport_code,
           util.undefined_stat_keys(c.sport_id, r.stats, false) AS undefined_raw_keys,
           util.undefined_stat_keys(c.sport_id, r.derived, true) AS undefined_derived_keys
    FROM rows r JOIN core.v_season_context c ON c.season_id = r.season_id
)
SELECT * FROM checked
WHERE undefined_raw_keys <> '{}' OR undefined_derived_keys <> '{}';

-- external_id_map 에서 가리키는 엔티티가 사라진 매핑
CREATE VIEW core.v_external_id_orphans AS
SELECT m.*
FROM ingest.external_id_map m
WHERE NOT CASE m.entity_type
    WHEN 'league' THEN EXISTS (SELECT 1 FROM core.league x WHERE x.id = m.entity_id)
    WHEN 'season' THEN EXISTS (SELECT 1 FROM core.season x WHERE x.id = m.entity_id)
    WHEN 'stage'  THEN EXISTS (SELECT 1 FROM core.competition_stage x WHERE x.id = m.entity_id)
    WHEN 'team'   THEN EXISTS (SELECT 1 FROM core.team x WHERE x.id = m.entity_id)
    WHEN 'player' THEN EXISTS (SELECT 1 FROM core.player x WHERE x.id = m.entity_id)
    WHEN 'venue'  THEN EXISTS (SELECT 1 FROM core.venue x WHERE x.id = m.entity_id)
    WHEN 'match'  THEN EXISTS (SELECT 1 FROM core.match x WHERE x.id = m.entity_id)
    ELSE false
END;
