DROP TABLE IF EXISTS analyst.saved_view;
DROP TABLE IF EXISTS analyst.manual_stat;
DROP TABLE IF EXISTS analyst.manual_upload;
DROP TABLE IF EXISTS analyst.custom_field;
DROP TABLE IF EXISTS analyst.custom_metric;
DROP TABLE IF EXISTS analyst.tag_assignment;
DROP TABLE IF EXISTS analyst.tag;
DROP TABLE IF EXISTS analyst.injury_note;
DROP TABLE IF EXISTS analyst.scouting_report;
DROP TABLE IF EXISTS analyst.scouting_template;
DROP TABLE IF EXISTS analyst.change_log;
DROP FUNCTION IF EXISTS util.analyst_template_before_update();
DROP FUNCTION IF EXISTS util.analyst_before_update();
DROP FUNCTION IF EXISTS util.analyst_audit();
DROP FUNCTION IF EXISTS util.has_workspace_role(integer, text[]);
ALTER TABLE ingest.id_match_candidate DROP CONSTRAINT IF EXISTS fk_id_match_candidate_resolved_by;
DROP TABLE IF EXISTS auth.refresh_token;
DROP TABLE IF EXISTS auth.workspace_member;
DROP TABLE IF EXISTS auth.workspace;
DROP TABLE IF EXISTS auth.app_user;
