-- =====================================================================
-- 0006 인증(auth) + 분석가 입력(analyst)
--  - 분석가 입력 데이터는 core 와 물리적으로 분리하고, 공통 엔티티 ID 로 결합한다.
--  - 모든 입력 행에 작성자/작성·수정 시각/버전을 두고, 변경 이력은 트리거가 change_log 에 남긴다.
--  - 공개 범위(private / workspace)는 RLS 로 DB 레벨에서도 강제한다.
-- =====================================================================

-- ---------------------------------------------------------------------
-- auth
-- ---------------------------------------------------------------------
CREATE TABLE auth.app_user (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email            text NOT NULL UNIQUE CHECK (email = lower(email) AND position('@' IN email) > 1),
    password_hash    text,                          -- argon2. NULL = 초대 후 미설정
    display_name     text NOT NULL,
    is_active        boolean NOT NULL DEFAULT true,
    is_system_admin  boolean NOT NULL DEFAULT false,  -- 플랫폼 운영(설정·수집 관리) 권한
    last_login_at    timestamptz,
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now()
);

-- 분석가 조직 (구단 분석팀, 매체 등). "팀 공유" = 워크스페이스 공유
CREATE TABLE auth.workspace (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug        text NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9][a-z0-9-]*$'),
    name        text NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

-- 워크스페이스 내 역할: admin(관리자) / analyst(분석가) / viewer(열람자)
CREATE TABLE auth.workspace_member (
    workspace_id  integer NOT NULL REFERENCES auth.workspace (id) ON DELETE CASCADE,
    user_id       integer NOT NULL REFERENCES auth.app_user (id) ON DELETE CASCADE,
    role          text NOT NULL CHECK (role IN ('admin', 'analyst', 'viewer')),
    created_at    timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (workspace_id, user_id)
);
CREATE INDEX ix_workspace_member_user ON auth.workspace_member (user_id);

CREATE TABLE auth.refresh_token (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     integer NOT NULL REFERENCES auth.app_user (id) ON DELETE CASCADE,
    token_hash  text NOT NULL UNIQUE,
    expires_at  timestamptz NOT NULL,
    revoked_at  timestamptz,
    user_agent  text,
    ip          inet,
    created_at  timestamptz NOT NULL DEFAULT now()
);

SELECT util.attach_updated_at_trigger(t)
FROM unnest(ARRAY['auth.app_user', 'auth.workspace']::regclass[]) AS t;

ALTER TABLE ingest.id_match_candidate
    ADD CONSTRAINT fk_id_match_candidate_resolved_by FOREIGN KEY (resolved_by) REFERENCES auth.app_user (id);

-- 현재 사용자가 워크스페이스에서 주어진 역할 중 하나를 갖는지 (RLS 정책에서 사용)
CREATE FUNCTION util.has_workspace_role(p_workspace_id integer, p_roles text[]) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = pg_catalog, pg_temp AS $$
    SELECT EXISTS (
        SELECT 1 FROM auth.workspace_member wm
        WHERE wm.workspace_id = p_workspace_id
          AND wm.user_id = util.current_app_user()
          AND wm.role = ANY (p_roles)
    )
$$;

-- ---------------------------------------------------------------------
-- 변경 이력
-- ---------------------------------------------------------------------
CREATE TABLE analyst.change_log (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name    text NOT NULL,
    row_id        bigint NOT NULL,
    workspace_id  integer,
    op            text NOT NULL CHECK (op IN ('INSERT', 'UPDATE', 'DELETE')),
    before        jsonb,
    after         jsonb,
    actor_id      integer,                          -- app.user_id 미설정(마이그레이션 등)이면 NULL
    txid          bigint NOT NULL DEFAULT txid_current(),
    at            timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_change_log_row ON analyst.change_log (table_name, row_id, at DESC);

-- 모든 analyst 테이블의 AFTER 트리거: 변경 전/후 스냅숏 기록
CREATE FUNCTION util.analyst_audit() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, pg_temp AS $$
DECLARE
    old_j jsonb := CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN to_jsonb(OLD) END;
    new_j jsonb := CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN to_jsonb(NEW) END;
    ref   jsonb := coalesce(new_j, old_j);
BEGIN
    INSERT INTO analyst.change_log (table_name, row_id, workspace_id, op, before, after, actor_id)
    VALUES (TG_TABLE_NAME, (ref ->> 'id')::bigint, (ref ->> 'workspace_id')::integer,
            TG_OP, old_j, new_j, util.current_app_user());
    RETURN NULL;
END $$;

-- 수정 시 메타데이터 강제: 작성자·작성 시각 보존, 수정자·수정 시각·버전 갱신, 워크스페이스 이동 금지
CREATE FUNCTION util.analyst_before_update() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.workspace_id IS DISTINCT FROM OLD.workspace_id THEN
        RAISE EXCEPTION '워크스페이스는 변경할 수 없습니다 (table=%, id=%)', TG_TABLE_NAME, OLD.id;
    END IF;
    NEW.created_by := OLD.created_by;
    NEW.created_at := OLD.created_at;
    NEW.updated_by := util.current_app_user();
    NEW.updated_at := now();
    NEW.version    := OLD.version + 1;
    RETURN NEW;
END $$;

-- ---------------------------------------------------------------------
-- 분석가 입력 테이블
--  공통 컬럼: workspace_id, visibility, created_by, created_at, updated_by, updated_at, version, deleted_at
-- ---------------------------------------------------------------------

-- 스카우팅 템플릿 (워크스페이스 관리자가 종목별로 정의). 버전별로 불변, 수정 = 새 버전
--  items 예: [{"code":"HIT","label":"컨택","group":"타격","scale":"20-80","required":true}, ...]
CREATE TABLE analyst.scouting_template (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id  integer NOT NULL REFERENCES auth.workspace (id),
    visibility    text NOT NULL DEFAULT 'workspace' CHECK (visibility = 'workspace'),
    sport_id      smallint NOT NULL REFERENCES config.sport (id),
    code          text NOT NULL CHECK (code ~ '^[a-z][a-z0-9_]*$'),
    version       integer NOT NULL DEFAULT 1 CHECK (version >= 1),
    name          text NOT NULL,
    items         jsonb NOT NULL CHECK (jsonb_typeof(items) = 'array'),
    is_active     boolean NOT NULL DEFAULT true,
    created_by    integer NOT NULL DEFAULT util.current_app_user() REFERENCES auth.app_user (id),
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_by    integer REFERENCES auth.app_user (id),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    row_version   integer NOT NULL DEFAULT 1,
    deleted_at    timestamptz,
    UNIQUE (workspace_id, sport_id, code, version)
);

-- 스카우팅 리포트
CREATE TABLE analyst.scouting_report (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id  integer NOT NULL REFERENCES auth.workspace (id),
    visibility    text NOT NULL DEFAULT 'private' CHECK (visibility IN ('private', 'workspace')),
    template_id   integer NOT NULL REFERENCES analyst.scouting_template (id),
    player_id     integer NOT NULL REFERENCES core.player (id),
    match_id      bigint REFERENCES core.match (id),
    report_date   date NOT NULL DEFAULT current_date,
    scores        jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(scores) = 'object'),
    summary       text,
    comment       text,
    created_by    integer NOT NULL DEFAULT util.current_app_user() REFERENCES auth.app_user (id),
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_by    integer REFERENCES auth.app_user (id),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    version       integer NOT NULL DEFAULT 1,
    deleted_at    timestamptz
);
CREATE INDEX ix_scouting_report_player ON analyst.scouting_report (player_id, report_date DESC);

-- 부상·컨디션 메모
CREATE TABLE analyst.injury_note (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id          integer NOT NULL REFERENCES auth.workspace (id),
    visibility            text NOT NULL DEFAULT 'private' CHECK (visibility IN ('private', 'workspace')),
    player_id             integer NOT NULL REFERENCES core.player (id),
    start_date            date NOT NULL,
    end_date              date,
    body_part             text,
    injury_type           text,
    severity              text NOT NULL DEFAULT 'unknown' CHECK (severity IN ('minor', 'moderate', 'severe', 'unknown')),
    status                text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'recovering', 'recovered', 'unknown')),
    source_note           text NOT NULL,            -- 정보 출처 (필수)
    expected_return_date  date,
    note                  text,
    created_by            integer NOT NULL DEFAULT util.current_app_user() REFERENCES auth.app_user (id),
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_by            integer REFERENCES auth.app_user (id),
    updated_at            timestamptz NOT NULL DEFAULT now(),
    version               integer NOT NULL DEFAULT 1,
    deleted_at            timestamptz,
    CHECK (end_date IS NULL OR end_date >= start_date)
);
CREATE INDEX ix_injury_note_player ON analyst.injury_note (player_id, start_date DESC);

-- 커스텀 태그
CREATE TABLE analyst.tag (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id  integer NOT NULL REFERENCES auth.workspace (id),
    visibility    text NOT NULL DEFAULT 'private' CHECK (visibility IN ('private', 'workspace')),
    name          text NOT NULL CHECK (length(name) BETWEEN 1 AND 50),
    color         text CHECK (color ~ '^#[0-9a-fA-F]{6}$'),
    created_by    integer NOT NULL DEFAULT util.current_app_user() REFERENCES auth.app_user (id),
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_by    integer REFERENCES auth.app_user (id),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    version       integer NOT NULL DEFAULT 1,
    deleted_at    timestamptz
);
CREATE UNIQUE INDEX uq_tag_shared ON analyst.tag (workspace_id, lower(name)) WHERE visibility = 'workspace';
CREATE UNIQUE INDEX uq_tag_private ON analyst.tag (workspace_id, created_by, lower(name)) WHERE visibility = 'private';

-- 태그 부착. 대상은 선수/팀/경기 중 정확히 하나 (다형 FK 대신 실제 FK 유지)
CREATE TABLE analyst.tag_assignment (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id  integer NOT NULL REFERENCES auth.workspace (id),
    tag_id        integer NOT NULL REFERENCES analyst.tag (id) ON DELETE CASCADE,
    player_id     integer REFERENCES core.player (id),
    team_id       integer REFERENCES core.team (id),
    match_id      bigint REFERENCES core.match (id),
    created_by    integer NOT NULL DEFAULT util.current_app_user() REFERENCES auth.app_user (id),
    created_at    timestamptz NOT NULL DEFAULT now(),
    CHECK (num_nonnulls(player_id, team_id, match_id) = 1)
);
CREATE UNIQUE INDEX uq_tag_assignment_player ON analyst.tag_assignment (tag_id, player_id) WHERE player_id IS NOT NULL;
CREATE UNIQUE INDEX uq_tag_assignment_team ON analyst.tag_assignment (tag_id, team_id) WHERE team_id IS NOT NULL;
CREATE UNIQUE INDEX uq_tag_assignment_match ON analyst.tag_assignment (tag_id, match_id) WHERE match_id IS NOT NULL;

-- 커스텀 지표 (기존 지표를 조합한 수식). code 는 cm. 접두어
CREATE TABLE analyst.custom_metric (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id        integer NOT NULL REFERENCES auth.workspace (id),
    visibility          text NOT NULL DEFAULT 'private' CHECK (visibility IN ('private', 'workspace')),
    sport_id            smallint NOT NULL REFERENCES config.sport (id),
    code                text NOT NULL CHECK (code ~ '^cm\.[A-Z][A-Z0-9_]*$'),
    name_ko             text NOT NULL,
    formula             text NOT NULL,
    depends_on          text[] NOT NULL DEFAULT '{}',
    scope               text NOT NULL DEFAULT 'player' CHECK (scope IN ('player', 'team', 'both')),
    levels              text[] NOT NULL DEFAULT '{season}'
                        CHECK (cardinality(levels) > 0 AND levels <@ ARRAY['period', 'match', 'season']::text[]),
    data_type           text NOT NULL DEFAULT 'decimal' CHECK (data_type IN ('int', 'decimal', 'ratio', 'percent')),
    decimals            smallint NOT NULL DEFAULT 3 CHECK (decimals BETWEEN 0 AND 6),
    higher_is_better    boolean,
    qualification_code  text,                       -- config.qualification_rule.code
    description         text,
    created_by          integer NOT NULL DEFAULT util.current_app_user() REFERENCES auth.app_user (id),
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_by          integer REFERENCES auth.app_user (id),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    version             integer NOT NULL DEFAULT 1,
    deleted_at          timestamptz,
    UNIQUE (workspace_id, code)
);

-- 분석가 정의 필드 (공개 데이터에 없는 수치: 자체 트래킹 등). code 는 cf. 접두어
CREATE TABLE analyst.custom_field (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id      integer NOT NULL REFERENCES auth.workspace (id),
    visibility        text NOT NULL DEFAULT 'workspace' CHECK (visibility IN ('private', 'workspace')),
    sport_id          smallint NOT NULL REFERENCES config.sport (id),
    code              text NOT NULL CHECK (code ~ '^cf\.[A-Z][A-Z0-9_]*$'),
    name_ko           text NOT NULL,
    data_type         text NOT NULL CHECK (data_type IN ('int', 'decimal', 'ratio', 'percent', 'duration', 'text')),
    aggregation       text NOT NULL DEFAULT 'sum' CHECK (aggregation IN ('sum', 'avg', 'max', 'min', 'last', 'none')),
    unit              text,
    decimals          smallint NOT NULL DEFAULT 0 CHECK (decimals BETWEEN 0 AND 6),
    higher_is_better  boolean,
    description       text,
    created_by        integer NOT NULL DEFAULT util.current_app_user() REFERENCES auth.app_user (id),
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_by        integer REFERENCES auth.app_user (id),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    version           integer NOT NULL DEFAULT 1,
    deleted_at        timestamptz,
    UNIQUE (workspace_id, code)
);

-- CSV 업로드 이력. 템플릿은 stat_definition + custom_field 로부터 런타임 생성
CREATE TABLE analyst.manual_upload (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id   integer NOT NULL REFERENCES auth.workspace (id),
    visibility     text NOT NULL DEFAULT 'private' CHECK (visibility IN ('private', 'workspace')),
    sport_id       smallint NOT NULL REFERENCES config.sport (id),
    target         text NOT NULL CHECK (target IN ('player_match', 'player_season', 'team_match', 'team_season')),
    file_name      text NOT NULL,
    file_sha256    char(64) NOT NULL,
    row_count      integer NOT NULL DEFAULT 0 CHECK (row_count >= 0),
    status         text NOT NULL DEFAULT 'validating'
                   CHECK (status IN ('validating', 'invalid', 'validated', 'applied', 'rolled_back')),
    errors         jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(errors) = 'array'),
    applied_count  integer NOT NULL DEFAULT 0 CHECK (applied_count >= 0),
    applied_at     timestamptz,
    created_by     integer NOT NULL DEFAULT util.current_app_user() REFERENCES auth.app_user (id),
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_by     integer REFERENCES auth.app_user (id),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    version        integer NOT NULL DEFAULT 1,
    deleted_at     timestamptz
);

-- 분석가 입력 수치 (CSV 업로드 또는 직접 입력). core 기록과 별도 저장, 화면에서 "분석가 입력"으로 구분
CREATE TABLE analyst.manual_stat (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id  integer NOT NULL REFERENCES auth.workspace (id),
    visibility    text NOT NULL DEFAULT 'private' CHECK (visibility IN ('private', 'workspace')),
    sport_id      smallint NOT NULL REFERENCES config.sport (id),
    upload_id     bigint REFERENCES analyst.manual_upload (id) ON DELETE CASCADE,  -- NULL = 직접 입력
    target        text NOT NULL CHECK (target IN ('player_match', 'player_season', 'team_match', 'team_season')),
    player_id     integer REFERENCES core.player (id),
    team_id       integer REFERENCES core.team (id),
    match_id      bigint REFERENCES core.match (id),
    period_id     bigint REFERENCES core.match_period (id),
    season_id     integer REFERENCES core.season (id),
    stage_id      integer REFERENCES core.competition_stage (id),
    stats         jsonb NOT NULL CHECK (jsonb_typeof(stats) = 'object'),
    note          text,
    created_by    integer NOT NULL DEFAULT util.current_app_user() REFERENCES auth.app_user (id),
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_by    integer REFERENCES auth.app_user (id),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    version       integer NOT NULL DEFAULT 1,
    deleted_at    timestamptz,
    CHECK (target NOT LIKE 'player\_%' OR player_id IS NOT NULL),
    CHECK (target NOT LIKE 'team\_%' OR team_id IS NOT NULL),
    CHECK (target NOT LIKE '%\_match' OR match_id IS NOT NULL),
    CHECK (target NOT LIKE '%\_season' OR season_id IS NOT NULL)
);
CREATE INDEX ix_manual_stat_player ON analyst.manual_stat (player_id) WHERE player_id IS NOT NULL;
CREATE INDEX ix_manual_stat_team ON analyst.manual_stat (team_id) WHERE team_id IS NOT NULL;

-- 저장된 뷰 (화면 상태 = URL 쿼리 파라미터 JSON)
CREATE TABLE analyst.saved_view (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id  integer NOT NULL REFERENCES auth.workspace (id),
    visibility    text NOT NULL DEFAULT 'private' CHECK (visibility IN ('private', 'workspace')),
    view_type     text NOT NULL CHECK (view_type ~ '^[a-z][a-z0-9_]*$'),
    name          text NOT NULL,
    state         jsonb NOT NULL CHECK (jsonb_typeof(state) = 'object'),
    created_by    integer NOT NULL DEFAULT util.current_app_user() REFERENCES auth.app_user (id),
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_by    integer REFERENCES auth.app_user (id),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    version       integer NOT NULL DEFAULT 1,
    deleted_at    timestamptz
);

-- scouting_template 은 버전 컬럼명이 템플릿 버전과 겹쳐 row_version 을 쓰므로 별도 트리거 함수
CREATE FUNCTION util.analyst_template_before_update() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.workspace_id IS DISTINCT FROM OLD.workspace_id THEN
        RAISE EXCEPTION '워크스페이스는 변경할 수 없습니다 (table=%, id=%)', TG_TABLE_NAME, OLD.id;
    END IF;
    NEW.created_by  := OLD.created_by;
    NEW.created_at  := OLD.created_at;
    NEW.updated_by  := util.current_app_user();
    NEW.updated_at  := now();
    NEW.row_version := OLD.row_version + 1;
    RETURN NEW;
END $$;

-- ---------------------------------------------------------------------
-- 트리거 부착
-- ---------------------------------------------------------------------
DO $$
DECLARE
    t text;
BEGIN
    -- 수정 메타데이터 트리거 (tag_assignment 는 삽입/삭제만 하므로 제외)
    FOREACH t IN ARRAY ARRAY['scouting_report', 'injury_note', 'tag', 'custom_metric', 'custom_field',
                             'manual_upload', 'manual_stat', 'saved_view'] LOOP
        EXECUTE 'CREATE TRIGGER trg_before_update BEFORE UPDATE ON analyst.' || quote_ident(t)
             || ' FOR EACH ROW EXECUTE FUNCTION util.analyst_before_update()';
    END LOOP;
    EXECUTE 'CREATE TRIGGER trg_before_update BEFORE UPDATE ON analyst.scouting_template'
         || ' FOR EACH ROW EXECUTE FUNCTION util.analyst_template_before_update()';

    -- 변경 이력 트리거 (change_log 제외 전체)
    FOREACH t IN ARRAY ARRAY['scouting_template', 'scouting_report', 'injury_note', 'tag', 'tag_assignment',
                             'custom_metric', 'custom_field', 'manual_upload', 'manual_stat', 'saved_view'] LOOP
        EXECUTE 'CREATE TRIGGER trg_audit AFTER INSERT OR UPDATE OR DELETE ON analyst.' || quote_ident(t)
             || ' FOR EACH ROW EXECUTE FUNCTION util.analyst_audit()';
    END LOOP;
END $$;

-- ---------------------------------------------------------------------
-- RLS (Row Level Security)
--  읽기: 본인 작성 또는 (workspace 공개 AND 워크스페이스 멤버)
--  쓰기: 본인 작성 행 + 분석가/관리자 역할, 관리자는 워크스페이스 공개 행 수정 가능
--  소프트 삭제(deleted_at) 필터는 API 계층에서 적용한다 (RLS 에 넣으면 소프트 삭제 UPDATE 가 막힘)
--  테이블 소유자(마이그레이션 계정)는 RLS 를 우회한다.
-- ---------------------------------------------------------------------
DO $$
DECLARE
    t text;
BEGIN
    FOREACH t IN ARRAY ARRAY['scouting_report', 'injury_note', 'tag', 'custom_metric', 'custom_field',
                             'manual_upload', 'manual_stat', 'saved_view'] LOOP
        EXECUTE 'ALTER TABLE analyst.' || quote_ident(t) || ' ENABLE ROW LEVEL SECURITY';
        EXECUTE 'CREATE POLICY p_select ON analyst.' || quote_ident(t) || ' FOR SELECT USING ('
             || ' created_by = util.current_app_user()'
             || ' OR (visibility = ''workspace'''
             || '     AND util.has_workspace_role(workspace_id, ARRAY[''admin'', ''analyst'', ''viewer''])))';
        EXECUTE 'CREATE POLICY p_insert ON analyst.' || quote_ident(t) || ' FOR INSERT WITH CHECK ('
             || ' created_by = util.current_app_user()'
             || ' AND util.has_workspace_role(workspace_id, ARRAY[''admin'', ''analyst'']))';
        EXECUTE 'CREATE POLICY p_update ON analyst.' || quote_ident(t) || ' FOR UPDATE USING ('
             || ' (created_by = util.current_app_user()'
             || '  AND util.has_workspace_role(workspace_id, ARRAY[''admin'', ''analyst'']))'
             || ' OR (visibility = ''workspace'' AND util.has_workspace_role(workspace_id, ARRAY[''admin''])))';
        EXECUTE 'CREATE POLICY p_delete ON analyst.' || quote_ident(t) || ' FOR DELETE USING ('
             || ' (created_by = util.current_app_user()'
             || '  AND util.has_workspace_role(workspace_id, ARRAY[''admin'', ''analyst'']))'
             || ' OR (visibility = ''workspace'' AND util.has_workspace_role(workspace_id, ARRAY[''admin''])))';
    END LOOP;
END $$;

-- 스카우팅 템플릿: 멤버 읽기, 워크스페이스 관리자만 쓰기
ALTER TABLE analyst.scouting_template ENABLE ROW LEVEL SECURITY;
CREATE POLICY p_select ON analyst.scouting_template FOR SELECT
    USING (util.has_workspace_role(workspace_id, ARRAY['admin', 'analyst', 'viewer']));
CREATE POLICY p_insert ON analyst.scouting_template FOR INSERT
    WITH CHECK (created_by = util.current_app_user() AND util.has_workspace_role(workspace_id, ARRAY['admin']));
-- 작성자는 트리거가 보존하므로 다른 관리자가 만든 템플릿도 수정 가능
CREATE POLICY p_update ON analyst.scouting_template FOR UPDATE
    USING (util.has_workspace_role(workspace_id, ARRAY['admin']));
CREATE POLICY p_delete ON analyst.scouting_template FOR DELETE
    USING (util.has_workspace_role(workspace_id, ARRAY['admin']));

-- 태그 부착: 보이는 태그에만, 부착 가시성은 태그 가시성을 따른다 (서브쿼리에도 tag 의 RLS 적용)
ALTER TABLE analyst.tag_assignment ENABLE ROW LEVEL SECURITY;
CREATE POLICY p_select ON analyst.tag_assignment FOR SELECT
    USING (EXISTS (SELECT 1 FROM analyst.tag t WHERE t.id = tag_id));
CREATE POLICY p_insert ON analyst.tag_assignment FOR INSERT
    WITH CHECK (created_by = util.current_app_user()
                AND util.has_workspace_role(workspace_id, ARRAY['admin', 'analyst'])
                AND EXISTS (SELECT 1 FROM analyst.tag t WHERE t.id = tag_id AND t.workspace_id = tag_assignment.workspace_id));
CREATE POLICY p_delete ON analyst.tag_assignment FOR DELETE
    USING (created_by = util.current_app_user()
           OR util.has_workspace_role(workspace_id, ARRAY['admin']));

-- 변경 이력: 본인 행위 또는 워크스페이스 관리자
ALTER TABLE analyst.change_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY p_select ON analyst.change_log FOR SELECT
    USING (actor_id = util.current_app_user()
           OR util.has_workspace_role(workspace_id, ARRAY['admin']));
